[[redirects]]
  from = "https://kubearmor.com/*"
  to = "https://kubearmor.io/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.kubearmor.com/*"
  to = "https://kubearmor.io/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://merry-gumdrop-b6f4e0.netlify.app/*"
  to = "https://kubearmor.io/:splat"
  status = 301
  force = true
