[[redirects]]
  from = "https://kubearmor.com/*"
  to = "https://kubearmor.io/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.kubearmor.com/*"
  to = "https://kubearmor.io/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://storied-selkie-270f20.netlify.app/*"
  to = "https://kubearmor.io/:splat"
  status = 301
  force = true
